/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdditionalDefensesTab: typeof import('./src/components/planner/AdditionalDefensesTab.vue')['default']
    AttributesCard: typeof import('./src/components/planner/AttributesCard.vue')['default']
    BlessingIcon: typeof import('./src/components/icons/BlessingIcon.vue')['default']
    BlessingsDialog: typeof import('./src/components/planner/BlessingsDialog.vue')['default']
    ClassIcon: typeof import('./src/components/icons/ClassIcon.vue')['default']
    CommonTab: typeof import('./src/components/planner/tabs/CommonTab.vue')['default']
    DefenseTab: typeof import('./src/components/planner/tabs/DefenseTab.vue')['default']
    GeneralTab: typeof import('./src/components/planner/tabs/GeneralTab.vue')['default']
    ItemCard: typeof import('./src/components/planner/ItemCard.vue')['default']
    ItemIcon: typeof import('./src/components/icons/ItemIcon.vue')['default']
    ItemsDialog: typeof import('./src/components/planner/ItemsDialog.vue')['default']
    ItemSlot: typeof import('./src/components/planner/ItemSlot.vue')['default']
    OffenseTab: typeof import('./src/components/planner/tabs/OffenseTab.vue')['default']
    ResistancesTab: typeof import('./src/components/planner/ResistancesTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
